// frontend/src/views/guest/login.vue
<template>
    <div>
      <loading v-if="state.loading" class="login-area">We are logging you in...</loading>
      <div v-if="!state.loading" class="login-area">
        <h1>Welcome to Habfort</h1>
        <p>A strange place with even stranger people!</p>
        <form @submit.prevent="login()">
          <div class="login_group">
            <label>Username</label>
            <input v-model="user.username" :class="{'login_error': state.error==='username'}" class="login_field">
          </div>
          <div class="login_group">
            <label>Password</label>
            <input v-model="user.password" :class="{'login_error': state.error==='password'}" class="login_field" type="password">
          </div>
          <div class="login_group" style="margin-top:-5%;">
            <button class="login-form__button">Let's go!</button>
          </div>
          <div class="login_group">
            <router-link :to="{ name: 'Guest.Register' }" class="login_link">Or Join Today...</router-link>
          </div>
        </form>
      </div>
    </div>  
</template>

<script>
import Session from '@/app/storage/session'
export default {
  data () {
    return {
      state: {
        loading: false,
        error: null
      },
      user: {
        username: '',
        password: ''
      }
    }
  },
  methods: {
    async login () {
      try {
        this.loading = false
        await Session.dispatch('start', this.user)
        this.$router.push({ name: 'Home.Me' })
      } catch (e) {
        console.log(e.response.data)
        this.state.error = e.response.data
        this.loading = false
      }
    }
  }
}
</script>

// web/src/heroic/pages/guest/login.tsx
import {Link} from 'react-router-dom'
import React, {Component} from 'react'
import Input from 'heroic/components/base/form/input'
import SessionActions from 'heroic/app/redux/actions/session'
import {withRouter, RouteComponentProps} from 'react-router-dom'

interface State {
	error: string | null,
	username: string,
	password: string,
	pending: boolean
}

class Login extends Component<RouteComponentProps> {

	state: State = {
		error: null,
		username: '',
		password: '',
		pending: false
	}

	onChange = (key: string, value: string | boolean): void => {
		this.setState({
			[key]: value
		})
	}

	onSubmit = async (event): Promise<void> => {
		event.preventDefault()
		const {username, password} = this.state

		try {
			this.onChange('pending', true)
			await SessionActions.attempt(username, password)
			this.props.history.push('/me')
		}
		catch (e) {
			this.onChange('pending', false)
			console.log(e)
		}
	}


	isDisabled = (): boolean => this.state.username === '' || this.state.password === ''

	render () {
		const {username, password} = this.state
		return (
			<div className="left-inner">
				<h1>Welcome to Habfort</h1>
				<p>A strange place with even stranger people!</p>
				<form onSubmit={this.onSubmit}>
					<div className="form-group">
						<label>Username</label>
						<Input column="username" type="text" value={username} onChange={this.onChange} />
					</div>
					<div className="form-group">
						<label>Password</label>
						<Input column="password" type="password" value={password} onChange={this.onChange} />
					</div>
					<button className="btn btn-green w-100" disabled={this.isDisabled()} type="submit">
						Let's go!
					</button>
				</form>
				<Link className="link" to="/register">Or Join Today...</Link>
			</div>
		)
	}

}

export default withRouter(Login)
